#!/usr/bin/env bash
clear
if [ $# != 4 ]; then
   echo "source ~<uid>/activate [Sub#] [Sct] [Assess] [Q#]<ENTER>"
   echo "   [Sub#]: Subject number like \"200\""
   echo "   [Sct]: Section like \"NAA\" or \"NBB\""
   echo "   [Assess]: Assessment Name like \"test\" or \"quiz\""
   echo "   [Q#]: Question number like \"3\" or \"11\""
else
   if [ $0 == $BASH_SOURCE ]; then
      echo "You forgot the \"source\" at the beginning of the submission command"
   else
      ~<uid>/getfiles $1 $2 $3 $4
      if [ $? == 0 ]; then
         cd ~/___$1$3___/$4
         echo ""
         echo "Open q$4.cpp with a text editor and start $3-$4"
         echo "BY FOLLOWING THE INSTRUCTIONS in q$4.cpp"
         echo "After you are done with this $3 question,"
         echo "issue the following command to submit your work:"
         echo "submit <ENTER>"
         alias submit="~<uid>/submit $1/$3/$2/$4"
      else
        if [ $? == 4 ]; then
           ~<uid>/submit $1/$3/$2/$4 -due
        fi
      fi
   fi
fi

