#!/bin/ksh

echo "This will give 711 permission to your home directory, are you sure?(Y/N)"
read resp
if [ $resp == Y ] || [ $resp == y ]; then
  echo "please wait, compiling"
  g++ -Wall -std=c++11 -o ~/getfiles assessMain.cpp  Command.cpp  Date.cpp  SubVals.cpp  Vals.cpp User.cpp
  cp activate ~/activate
  chmod 711 ~/.
  chmod 711 ~/submit
  chmod 755 ~/activate
  echo "Permissions set"
  echo "installation complete"
else
  echo "aborted"
fi
